// <auto-generated />
using System;
using Acorn.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acorn.Database.Migrations;

[DbContext(typeof(AcornDbContext))]
[Migration("20260912182944_InitialCreate")]
partial class _20260912182944_InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118");

        modelBuilder.Entity("Acorn.Database.Models.Account", b =>
            {
                b.Property<string>("Username")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("Country")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Created")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("LastUsed")
                    .HasColumnType("TEXT");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Salt")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Username");

                b.ToTable("Accounts");
            });

        modelBuilder.Entity("Acorn.Database.Models.BoardPost", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("AuthorAdmin")
                    .HasColumnType("INTEGER");

                b.Property<int>("BoardId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Body")
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnType("TEXT");

                b.Property<string>("CharacterName")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CharacterName");

                b.HasIndex("BoardId", "Id");

                b.ToTable("BoardPosts");
            });

        modelBuilder.Entity("Acorn.Database.Models.Character", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Accounts_Username")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("Accuracy")
                    .HasColumnType("INTEGER");

                b.Property<int>("Admin")
                    .HasColumnType("INTEGER");

                b.Property<int>("Agi")
                    .HasColumnType("INTEGER");

                b.Property<int>("Armor")
                    .HasColumnType("INTEGER");

                b.Property<int>("BankMax")
                    .HasColumnType("INTEGER");

                b.Property<int>("Cha")
                    .HasColumnType("INTEGER");

                b.Property<int>("Class")
                    .HasColumnType("INTEGER");

                b.Property<int>("Con")
                    .HasColumnType("INTEGER");

                b.Property<int>("Direction")
                    .HasColumnType("INTEGER");

                b.Property<int>("Evade")
                    .HasColumnType("INTEGER");

                b.Property<int>("Exp")
                    .HasColumnType("INTEGER");

                b.Property<string>("Fiance")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("Gender")
                    .HasColumnType("INTEGER");

                b.Property<int>("GoldBank")
                    .HasColumnType("INTEGER");

                b.Property<int>("HairColor")
                    .HasColumnType("INTEGER");

                b.Property<int>("HairStyle")
                    .HasColumnType("INTEGER");

                b.Property<bool>("Hidden")
                    .HasColumnType("INTEGER");

                b.Property<string>("Home")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("Hp")
                    .HasColumnType("INTEGER");

                b.Property<int>("Int")
                    .HasColumnType("INTEGER")
                    .HasColumnName("\"Int\"");

                b.Property<int>("Karma")
                    .HasColumnType("INTEGER");

                b.Property<int>("Level")
                    .HasColumnType("INTEGER");

                b.Property<int>("Map")
                    .HasColumnType("INTEGER");

                b.Property<int>("MaxDamage")
                    .HasColumnType("INTEGER");

                b.Property<int>("MaxHp")
                    .HasColumnType("INTEGER");

                b.Property<int>("MaxSp")
                    .HasColumnType("INTEGER");

                b.Property<int>("MaxTp")
                    .HasColumnType("INTEGER");

                b.Property<int>("MaxWeight")
                    .HasColumnType("INTEGER");

                b.Property<int>("MinDamage")
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<bool>("NoInteract")
                    .HasColumnType("INTEGER");

                b.Property<string>("Partner")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("Race")
                    .HasColumnType("INTEGER");

                b.Property<int>("SitState")
                    .HasColumnType("INTEGER");

                b.Property<int>("SkillPoints")
                    .HasColumnType("INTEGER");

                b.Property<int>("Sp")
                    .HasColumnType("INTEGER");

                b.Property<int>("StatPoints")
                    .HasColumnType("INTEGER");

                b.Property<int>("Str")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("Tp")
                    .HasColumnType("INTEGER");

                b.Property<int>("Usage")
                    .HasColumnType("INTEGER");

                b.Property<int>("Wis")
                    .HasColumnType("INTEGER");

                b.Property<int>("X")
                    .HasColumnType("INTEGER");

                b.Property<int>("Y")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Accounts_Username");

                b.ToTable("Characters");
            });

        modelBuilder.Entity("Acorn.Database.Models.CharacterItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("Amount")
                    .HasColumnType("INTEGER");

                b.Property<string>("CharacterName")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("ItemId")
                    .HasColumnType("INTEGER");

                b.Property<int>("Slot")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CharacterName", "Slot");

                b.ToTable("CharacterItems");
            });

        modelBuilder.Entity("Acorn.Database.Models.CharacterPaperdoll", b =>
            {
                b.Property<string>("CharacterName")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("Accessory")
                    .HasColumnType("INTEGER");

                b.Property<int>("Armlet1")
                    .HasColumnType("INTEGER");

                b.Property<int>("Armlet2")
                    .HasColumnType("INTEGER");

                b.Property<int>("Armor")
                    .HasColumnType("INTEGER");

                b.Property<int>("Belt")
                    .HasColumnType("INTEGER");

                b.Property<int>("Boots")
                    .HasColumnType("INTEGER");

                b.Property<int>("Bracer1")
                    .HasColumnType("INTEGER");

                b.Property<int>("Bracer2")
                    .HasColumnType("INTEGER");

                b.Property<int>("Gloves")
                    .HasColumnType("INTEGER");

                b.Property<int>("Hat")
                    .HasColumnType("INTEGER");

                b.Property<int>("Necklace")
                    .HasColumnType("INTEGER");

                b.Property<int>("Ring1")
                    .HasColumnType("INTEGER");

                b.Property<int>("Ring2")
                    .HasColumnType("INTEGER");

                b.Property<int>("Shield")
                    .HasColumnType("INTEGER");

                b.Property<int>("Weapon")
                    .HasColumnType("INTEGER");

                b.HasKey("CharacterName");

                b.ToTable("CharacterPaperdolls");
            });

        modelBuilder.Entity("Acorn.Database.Models.CharacterSpell", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CharacterName")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("Level")
                    .HasColumnType("INTEGER");

                b.Property<int>("SpellId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CharacterName");

                b.HasIndex("CharacterName", "SpellId")
                    .IsUnique();

                b.ToTable("CharacterSpells");
            });

        modelBuilder.Entity("Acorn.Database.Models.Guild", b =>
            {
                b.Property<string>("Tag")
                    .HasMaxLength(3)
                    .HasColumnType("TEXT");

                b.Property<int>("Bank")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Ranks")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.HasKey("Tag");

                b.ToTable("Guilds");
            });

        modelBuilder.Entity("Acorn.Database.Models.GuildMember", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CharacterName")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<string>("GuildTag")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("TEXT");

                b.Property<int>("RankIndex")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CharacterName")
                    .IsUnique();

                b.HasIndex("GuildTag");

                b.ToTable("GuildMembers");
            });

        modelBuilder.Entity("Acorn.Database.Models.QuestProgress", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CharacterName")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT");

                b.Property<int>("Completions")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("DoneAt")
                    .HasColumnType("TEXT");

                b.Property<string>("NpcKillsJson")
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnType("TEXT");

                b.Property<int>("PlayerKills")
                    .HasColumnType("INTEGER");

                b.Property<int>("QuestId")
                    .HasColumnType("INTEGER");

                b.Property<int>("State")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("CharacterName");

                b.HasIndex("CharacterName", "QuestId")
                    .IsUnique();

                b.ToTable("QuestProgress");
            });

        modelBuilder.Entity("Acorn.Database.Models.Character", b =>
            {
                b.HasOne("Acorn.Database.Models.Account", null)
                    .WithMany("Characters")
                    .HasForeignKey("Accounts_Username")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Acorn.Database.Models.CharacterItem", b =>
            {
                b.HasOne("Acorn.Database.Models.Character", null)
                    .WithMany("Items")
                    .HasForeignKey("CharacterName")
                    .HasPrincipalKey("Name")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Acorn.Database.Models.CharacterPaperdoll", b =>
            {
                b.HasOne("Acorn.Database.Models.Character", "Character")
                    .WithOne("Paperdoll")
                    .HasForeignKey("Acorn.Database.Models.CharacterPaperdoll", "CharacterName")
                    .HasPrincipalKey("Acorn.Database.Models.Character", "Name")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Character");
            });

        modelBuilder.Entity("Acorn.Database.Models.CharacterSpell", b =>
            {
                b.HasOne("Acorn.Database.Models.Character", null)
                    .WithMany("Spells")
                    .HasForeignKey("CharacterName")
                    .HasPrincipalKey("Name")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Acorn.Database.Models.GuildMember", b =>
            {
                b.HasOne("Acorn.Database.Models.Guild", "Guild")
                    .WithMany("Members")
                    .HasForeignKey("GuildTag")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Guild");
            });

        modelBuilder.Entity("Acorn.Database.Models.QuestProgress", b =>
            {
                b.HasOne("Acorn.Database.Models.Character", null)
                    .WithMany("QuestProgress")
                    .HasForeignKey("CharacterName")
                    .HasPrincipalKey("Name")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Acorn.Database.Models.Account", b =>
            {
                b.Navigation("Characters");
            });

        modelBuilder.Entity("Acorn.Database.Models.Character", b =>
            {
                b.Navigation("Items");

                b.Navigation("Paperdoll");

                b.Navigation("QuestProgress");

                b.Navigation("Spells");
            });

        modelBuilder.Entity("Acorn.Database.Models.Guild", b =>
            {
                b.Navigation("Members");
            });
#pragma warning restore 612, 618
    }
}
